

line-length = 120
indent-width = 4

exclude = [
    "__pycache__",
    ".git",
    ".venv",
    "_old",
    "_tmp",
]

[lint]
select = [
    "ALL"
]
ignore = [
    "ERA001",
]

[per-file-ignores]
"tests/**/*.py" = [
    "ANN401",
    "D102",
    "D103",
    "PLR2004",
    "S101",
]

[isort]
known-first-party = ["programming_bitcoin"]
lines-after-imports = 3


